# Generated by Django 5.0.14 on 2026-08-26 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer_name", models.CharField(max_length=120)),
                ("customer_title_ar", models.CharField(blank=True, max_length=120)),
                ("customer_title_en", models.CharField(blank=True, max_length=120)),
                ("content_ar", models.TextField()),
                ("content_en", models.TextField()),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("avatar_image", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FLIGHT", "Flight"),
                            ("HOTEL", "Hotel"),
                            ("PACKAGE", "Package"),
                            ("VISA", "Visa"),
                            ("CRUISE", "Cruise"),
                            ("CORPORATE", "Corporate"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_visible", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("order", "-created_at"),
            },
        ),
    ]
