# Generated by Django 5.0.14 on 2026-08-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_ar", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description_ar", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("FLIGHT", "Flight"),
                            ("HOTEL", "Hotel"),
                            ("PACKAGE", "Package"),
                            ("VISA", "Visa"),
                            ("CRUISE", "Cruise"),
                            ("CORPORATE", "Corporate"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price_before",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "price_after",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("image", models.URLField(blank=True, max_length=500, null=True)),
                ("starts_at", models.DateField()),
                ("ends_at", models.DateField()),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("-is_featured", "-starts_at"),
            },
        ),
    ]
