# Generated by Django 5.0.14 on 2026-08-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label_ar', models.CharField(max_length=150)),
                ('label_en', models.CharField(max_length=150)),
                ('href', models.CharField(max_length=200)),
                ('group', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], default='PRIMARY', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('group', 'order', 'id'),
            },
        ),
    ]
