# Generated by Django 5.0.14 on 2026-09-06 22:40

import apps.services.models.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="link",
            field=models.CharField(
                blank=True,
                max_length=200,
                validators=[apps.services.models.service.validate_internal_path],
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("car", "Car"),
                    ("transfer", "Airport shuttle"),
                    ("licence", "Driving licence"),
                    ("shield", "Shield (insurance)"),
                    ("sim", "SIM card"),
                    ("ticket", "Ticket"),
                    ("passport", "Passport"),
                    ("headset", "Headset (support)"),
                    ("plane", "Aeroplane"),
                    ("bed", "Bed (hotel)"),
                    ("ship", "Ship (cruise)"),
                    ("globe", "Globe"),
                    ("bag", "Luggage"),
                    ("map", "Map"),
                    ("pin", "Map pin"),
                    ("calendar", "Calendar"),
                    ("clock", "Clock"),
                    ("users", "People"),
                    ("meal", "Meal"),
                    ("tag", "Price tag"),
                    ("gift", "Gift"),
                    ("book", "Book (study)"),
                    ("mosque", "Mosque (Umrah)"),
                ],
                max_length=50,
            ),
        ),
    ]
