# Generated by Django 5.0.14 on 2026-09-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_link_alter_service_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FLIGHT", "Flight"),
                    ("HOTEL", "Hotel"),
                    ("PACKAGE", "Package"),
                    ("VISA", "Visa"),
                    ("CRUISE", "Cruise"),
                    ("CORPORATE", "Corporate"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
