# Generated by Django 5.0.14 on 2026-09-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_service_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_on_contact_form",
            field=models.BooleanField(default=False),
        ),
    ]
