# Generated by Django 5.0.14 on 2026-08-25 20:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("destinations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number in international format, e.g. +966501234567.",
                                regex="^\\+?[1-9]\\d{6,14}$",
                            )
                        ],
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("FLIGHT", "Flight"),
                            ("HOTEL", "Hotel"),
                            ("PACKAGE", "Package"),
                            ("VISA", "Visa"),
                            ("CRUISE", "Cruise"),
                            ("CORPORATE", "Corporate"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("travel_date", models.DateField(blank=True, null=True)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("CONTACTED", "Contacted"),
                            ("QUALIFIED", "Qualified"),
                            ("CONVERTED", "Converted"),
                            ("CLOSED", "Closed"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("WEBSITE", "Website"),
                            ("PHONE", "Phone"),
                            ("WHATSAPP", "WhatsApp"),
                            ("REFERRAL", "Referral"),
                            ("OTHER", "Other"),
                        ],
                        default="WEBSITE",
                        max_length=20,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to="destinations.destination",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "inquiries",
                "ordering": ("-created_at",),
            },
        ),
    ]
