# Generated by Django 5.0.14 on 2026-08-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="details",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
