# Generated by Django 5.0.14 on 2026-09-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0002_inquiry_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="InquiryField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("FLIGHT", "Flight"),
                            ("HOTEL", "Hotel"),
                            ("PACKAGE", "Package"),
                            ("VISA", "Visa"),
                            ("CRUISE", "Cruise"),
                            ("CORPORATE", "Corporate"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("key", models.SlugField(max_length=40)),
                ("label_ar", models.CharField(max_length=120)),
                ("label_en", models.CharField(max_length=120)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Short text"),
                            ("TEXTAREA", "Long text"),
                            ("NUMBER", "Number"),
                            ("DATE", "Date"),
                            ("SELECT", "Choice from a list"),
                        ],
                        default="TEXT",
                        max_length=10,
                    ),
                ),
                ("placeholder_ar", models.CharField(blank=True, max_length=160)),
                ("placeholder_en", models.CharField(blank=True, max_length=160)),
                ("options_ar", models.TextField(blank=True)),
                ("options_en", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("service_type", "order", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="inquiryfield",
            constraint=models.UniqueConstraint(
                fields=("service_type", "key"), name="unique_inquiry_field_key_per_service"
            ),
        ),
    ]
