# Generated by Django 5.0.14 on 2026-09-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0003_inquiryfield_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiryfield",
            name="group_ar",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="inquiryfield",
            name="group_en",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="inquiryfield",
            name="is_wide",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inquiryfield",
            name="max_value",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inquiryfield",
            name="min_value",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inquiryfield",
            name="not_before",
            field=models.SlugField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="inquiryfield",
            name="not_past",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inquiryfield",
            name="show_when_key",
            field=models.SlugField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="inquiryfield",
            name="show_when_value",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="inquiryfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Short text"),
                    ("TEXTAREA", "Long text"),
                    ("NUMBER", "Number"),
                    ("DATE", "Date"),
                    ("SELECT", "Choice from a list"),
                    ("STEPPER", "Count with − and + buttons"),
                    ("SEGMENTED", "Choice laid out as buttons"),
                    ("CHECKBOX", "Several choices at once"),
                    ("AIRPORT", "Airport search (keeps the code)"),
                    ("CITY", "City search"),
                ],
                default="TEXT",
                max_length=10,
            ),
        ),
    ]
