# Generated by Django 5.0.14 on 2026-09-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0004_inquiryfield_group_ar_inquiryfield_group_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InquiryServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("FLIGHT", "Flight"),
                            ("HOTEL", "Hotel"),
                            ("PACKAGE", "Package"),
                            ("VISA", "Visa"),
                            ("CRUISE", "Cruise"),
                            ("CORPORATE", "Corporate"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("label_ar", models.CharField(max_length=80)),
                ("label_en", models.CharField(max_length=80)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("order", "value"),
            },
        ),
    ]
