# Generated by Django 5.0.14 on 2026-09-07 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0005_inquiryservicetype"),
        ("services", "0004_service_is_on_contact_form"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="inquiryfield",
            name="unique_inquiry_field_key_per_service",
        ),
        migrations.AddField(
            model_name="inquiryfield",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiry_fields",
                to="services.service",
            ),
        ),
        migrations.AlterField(
            model_name="inquiryfield",
            name="service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FLIGHT", "Flight"),
                    ("HOTEL", "Hotel"),
                    ("PACKAGE", "Package"),
                    ("VISA", "Visa"),
                    ("CRUISE", "Cruise"),
                    ("CORPORATE", "Corporate"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="inquiryfield",
            constraint=models.UniqueConstraint(
                condition=models.Q(("service__isnull", True)),
                fields=("service_type", "key"),
                name="unique_inquiry_field_key_per_service_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="inquiryfield",
            constraint=models.UniqueConstraint(
                condition=models.Q(("service__isnull", False)),
                fields=("service", "key"),
                name="unique_inquiry_field_key_per_service",
            ),
        ),
        migrations.AddConstraint(
            model_name="inquiryfield",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("service__isnull", False),
                    models.Q(("service_type", ""), _negated=True),
                    _connector="OR",
                ),
                name="inquiry_field_belongs_to_something",
            ),
        ),
    ]
