# Generated by Django 5.0.14 on 2026-09-07 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0006_remove_inquiryfield_unique_inquiry_field_key_per_service_and_more"),
        ("services", "0004_service_is_on_contact_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inquiries",
                to="services.service",
            ),
        ),
    ]
