# Generated by Django 5.0.14 on 2026-08-25 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VisaCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_ar", models.CharField(max_length=150)),
                ("name_en", models.CharField(max_length=150)),
                ("flag_image", models.ImageField(blank=True, null=True, upload_to="visas/flags/")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "visa countries",
                "ordering": ("name_en",),
            },
        ),
        migrations.CreateModel(
            name="VisaType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_ar", models.CharField(max_length=150)),
                ("name_en", models.CharField(max_length=150)),
                ("requirements_ar", models.TextField(blank=True)),
                ("requirements_en", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("processing_time_days", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visa_types",
                        to="visas.visacountry",
                    ),
                ),
            ],
            options={
                "ordering": ("country", "name_en"),
            },
        ),
    ]
