# Generated by Django 5.0.14 on 2026-08-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visacountry",
            name="flag_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
