# Generated by Django 5.0.14 on 2026-08-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0002_alter_visacountry_flag_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='visatype',
            name='validity_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
