# Generated by Django 5.0.14 on 2026-08-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0003_visatype_validity_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='visatype',
            name='purpose',
            field=models.CharField(blank=True, choices=[('TOURISM', 'Tourism'), ('BUSINESS', 'Business'), ('STUDY', 'Study'), ('UMRAH', 'Umrah'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
