# Generated by Django 5.0.14 on 2026-09-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visas", "0004_visatype_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="visatype",
            name="entry_type",
            field=models.CharField(
                blank=True,
                choices=[("SINGLE", "Single entry"), ("MULTIPLE", "Multiple entry")],
                max_length=10,
            ),
        ),
    ]
