# Generated by Django 5.0.14 on 2026-09-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visas", "0005_visatype_entry_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="visacountry",
            name="cover_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="visatype",
            name="cover_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
