# Generated by Django 5.0.14 on 2026-08-27 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0002_alter_destination_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_ar', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('cruise_line_ar', models.CharField(blank=True, max_length=150)),
                ('cruise_line_en', models.CharField(blank=True, max_length=150)),
                ('departure_port_ar', models.CharField(blank=True, max_length=150)),
                ('departure_port_en', models.CharField(blank=True, max_length=150)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('duration_nights', models.PositiveIntegerField(default=1)),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True)),
                ('included_services_ar', models.TextField(blank=True)),
                ('included_services_en', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cruises', to='destinations.destination')),
            ],
            options={
                'ordering': ('-is_featured', 'price_from'),
            },
        ),
        migrations.CreateModel(
            name='CruiseItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_number', models.PositiveIntegerField()),
                ('port_ar', models.CharField(max_length=150)),
                ('port_en', models.CharField(max_length=150)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='cruises.cruise')),
            ],
            options={
                'verbose_name_plural': 'cruise itineraries',
                'ordering': ('cruise', 'day_number'),
            },
        ),
        migrations.AddConstraint(
            model_name='cruiseitinerary',
            constraint=models.UniqueConstraint(fields=('cruise', 'day_number'), name='unique_cruise_day'),
        ),
    ]
