# Generated by Django 5.0.14 on 2026-08-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
