# Generated by Django 5.0.14 on 2026-09-06 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cruises", "0002_cruise_departure_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="CruisePort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=60, unique=True)),
                ("name_ar", models.CharField(max_length=150)),
                ("name_en", models.CharField(max_length=150)),
                ("city_ar", models.CharField(max_length=120)),
                ("city_en", models.CharField(max_length=120)),
                ("country_ar", models.CharField(max_length=120)),
                ("country_en", models.CharField(max_length=120)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("is_popular", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("city_ar_folded", models.CharField(blank=True, db_index=True, max_length=120)),
                ("text_ar_folded", models.CharField(blank=True, max_length=400)),
            ],
            options={
                "ordering": ("-is_popular", "order", "country_en", "city_en"),
                "indexes": [
                    models.Index(fields=["country_code"], name="cruises_cru_country_b86d1a_idx"),
                    models.Index(fields=["city_en"], name="cruises_cru_city_en_ed357b_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="cruise",
            name="departure_port",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cruises",
                to="cruises.cruiseport",
            ),
        ),
    ]
