# Generated by Django 5.0.14 on 2026-09-07 17:21

from django.db import migrations, models


def fill_folded(apps, schema_editor):
    """Backfill the rows already in the table.

    Computed here rather than by re-saving: a historical model carries no
    custom save(), so the fields would come back empty.
    """
    from common.utilities import normalize_latin

    CruisePort = apps.get_model("cruises", "CruisePort")
    rows = list(CruisePort.objects.all())
    for row in rows:
        row.city_en_folded = normalize_latin(row.city_en)
        row.text_en_folded = normalize_latin(f"{row.name_en} {row.country_en}")
    CruisePort.objects.bulk_update(rows, ["city_en_folded", "text_en_folded"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("cruises", "0003_cruiseport_cruise_departure_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="cruiseport",
            name="city_en_folded",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name="cruiseport",
            name="text_en_folded",
            field=models.CharField(blank=True, max_length=400),
        ),
            migrations.RunPython(fill_folded, migrations.RunPython.noop),
    ]
