# Generated by Django 5.0.14 on 2026-08-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_package_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='included_services_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='included_services_en',
            field=models.TextField(blank=True),
        ),
    ]
