# Generated by Django 5.0.14 on 2026-09-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_seed_from_site_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="branch",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
