# Generated by Django 5.0.14 on 2026-09-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_branch_is_main_branch_latitude_branch_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_ar", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200)),
                ("description_ar", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("badge_ar", models.CharField(blank=True, max_length=40)),
                ("badge_en", models.CharField(blank=True, max_length=40)),
                ("code", models.CharField(blank=True, max_length=30)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("TAG", "Discount tag"),
                            ("CLOCK", "Countdown"),
                            ("GIFT", "Referral gift"),
                        ],
                        default="TAG",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
    ]
