# Generated by Django 5.0.14 on 2026-09-06 23:33

import common.validators.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_promotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="cta_label_ar",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="promotion",
            name="cta_label_en",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="promotion",
            name="link",
            field=models.CharField(
                blank=True,
                max_length=200,
                validators=[common.validators.paths.validate_internal_path],
            ),
        ),
    ]
