# Generated by Django 5.0.14 on 2026-09-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_promobar"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="google_maps_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
