# Generated by Django 5.0.14 on 2026-09-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_branch_google_maps_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="working_hours_ar",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="branch",
            name="working_hours_en",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
