# Generated by Django 5.0.14 on 2026-09-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_branch_working_hours_ar_branch_working_hours_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="cover_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
