# Generated by Django 5.0.14 on 2026-08-26 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlightDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_ar", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("origin_city_ar", models.CharField(max_length=100)),
                ("origin_city_en", models.CharField(max_length=100)),
                (
                    "origin_airport_code",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a 3-letter IATA airport code, e.g. JED.",
                                regex="^[A-Za-z]{3}$",
                            )
                        ],
                    ),
                ),
                ("destination_city_ar", models.CharField(max_length=100)),
                ("destination_city_en", models.CharField(max_length=100)),
                (
                    "destination_airport_code",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a 3-letter IATA airport code, e.g. JED.",
                                regex="^[A-Za-z]{3}$",
                            )
                        ],
                    ),
                ),
                ("airline_name_ar", models.CharField(blank=True, max_length=120)),
                ("airline_name_en", models.CharField(blank=True, max_length=120)),
                ("airline_logo", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("ONE_WAY", "One way"),
                            ("ROUND_TRIP", "Round trip"),
                            ("MULTI_CITY", "Multi city"),
                        ],
                        default="ROUND_TRIP",
                        max_length=20,
                    ),
                ),
                (
                    "cabin_class",
                    models.CharField(
                        choices=[
                            ("ECONOMY", "Economy"),
                            ("PREMIUM_ECONOMY", "Premium economy"),
                            ("BUSINESS", "Business"),
                            ("FIRST", "First"),
                        ],
                        default="ECONOMY",
                        max_length=20,
                    ),
                ),
                ("price_from", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="SAR", max_length=3)),
                ("departure_date", models.DateField(blank=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                ("baggage_allowance_kg", models.PositiveIntegerField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("-is_featured", "price_from"),
            },
        ),
    ]
