# Generated by Django 5.0.14 on 2026-09-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightdeal",
            name="cover_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
