# Generated by Django 5.0.14 on 2026-08-28 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iata_code', models.CharField(db_index=True, max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a 3-letter IATA airport code, e.g. JED.', regex='^[A-Za-z]{3}$')])),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('city_ar', models.CharField(max_length=120)),
                ('city_en', models.CharField(max_length=120)),
                ('country_ar', models.CharField(max_length=120)),
                ('country_en', models.CharField(max_length=120)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-is_popular', 'order', 'city_en', 'iata_code'),
                'indexes': [models.Index(fields=['city_en'], name='airports_ai_city_en_3fc689_idx'), models.Index(fields=['city_ar'], name='airports_ai_city_ar_235105_idx')],
            },
        ),
    ]
