# Generated by Django 5.0.14 on 2026-08-28 08:25

from django.db import migrations, models


def fill_folded(apps, schema_editor):
    """Backfill the rows the catalogue migration already wrote.

    Computed here rather than by re-saving: a historical model carries no
    custom save(), so the fields would come back empty.
    """
    from common.utilities import normalize_arabic

    Airport = apps.get_model("airports", "Airport")
    rows = list(Airport.objects.all())
    for row in rows:
        row.city_ar_folded = normalize_arabic(row.city_ar)
        row.text_ar_folded = normalize_arabic(f"{row.name_ar} {row.country_ar}")
    Airport.objects.bulk_update(rows, ["city_ar_folded", "text_ar_folded"], batch_size=200)


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0002_seed_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='city_ar_folded',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='airport',
            name='text_ar_folded',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.RunPython(fill_folded, migrations.RunPython.noop),
    ]
