# Generated by Django 5.0.14 on 2026-09-07 17:15

from django.db import migrations, models


def fill_folded(apps, schema_editor):
    """Backfill the rows already in the table.

    Computed here rather than by re-saving: a historical model carries no
    custom save(), so the fields would come back empty.
    """
    from common.utilities import normalize_latin

    Airport = apps.get_model("airports", "Airport")
    rows = list(Airport.objects.all())
    for row in rows:
        row.city_en_folded = normalize_latin(row.city_en)
        row.text_en_folded = normalize_latin(f"{row.name_en} {row.country_en}")
    Airport.objects.bulk_update(rows, ["city_en_folded", "text_en_folded"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("airports", "0003_folded_arabic_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="city_en_folded",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name="airport",
            name="text_en_folded",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.RunPython(fill_folded, migrations.RunPython.noop),
    ]
