# Generated by Django 5.0.14 on 2026-08-26 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page_key",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("destinations", "Destinations"),
                            ("packages", "Packages"),
                            ("visas", "Visas"),
                            ("flights", "Flights"),
                            ("hotels", "Hotels"),
                            ("cruises", "Cruises"),
                            ("offers", "Offers"),
                            ("corporate", "Corporate"),
                            ("about", "About"),
                            ("contact", "Contact"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("NONE", "Brand gradient"),
                            ("IMAGE", "Image"),
                            ("VIDEO", "Video"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("video_url", models.URLField(blank=True, max_length=500)),
                ("poster_url", models.URLField(blank=True, max_length=500)),
                (
                    "overlay_opacity",
                    models.PositiveSmallIntegerField(
                        default=55, validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                ("eyebrow_ar", models.CharField(blank=True, max_length=120)),
                ("eyebrow_en", models.CharField(blank=True, max_length=120)),
                ("title_ar", models.CharField(blank=True, max_length=200)),
                ("title_en", models.CharField(blank=True, max_length=200)),
                ("subtitle_ar", models.TextField(blank=True)),
                ("subtitle_en", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "page hero",
                "verbose_name_plural": "page heroes",
                "ordering": ("page_key",),
            },
        ),
    ]
