# Generated by Django 5.0.14 on 2026-08-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pagehero'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('SERVICES', 'What we offer'), ('EXPLORER', 'Budget explorer'), ('DESTINATIONS', 'Popular destinations'), ('PACKAGES', 'Featured packages'), ('OFFERS', 'Offers'), ('VISAS', 'Visa services'), ('CRUISES', 'Cruises'), ('TRUST', 'Why travel with us'), ('PARTNERS', 'Partners'), ('TESTIMONIALS', 'Testimonials'), ('CTA', 'Closing call to action')], max_length=32, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order', 'key'),
            },
        ),
    ]
